server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: greendb
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: sky
    password: sky1234
    url: jdbc:mariadb://localhost:3306/skydb?serverTimezone=Asia/Seoul
  
  
  
  jpa:
    open-in-view: true  
    hibernate:
      ddl-auto: none # create, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
